version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./Backend
    volumes:
      - ./backend:/app

  bigdata:
    build:
      dockerfile: Dockerfile
      context: ./bigdata
    volumes:
      - ./bigdata:/app
