spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    username: ubuntu
    url: jdbc:mysql://j5a303.p.ssafy.io:3306/buki?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        show-sql: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: j5a303.p.ssafy.io

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: "*"
  max-age: 3600

jwt:
  header: Authorization
  secret:
  token-validity-in-seconds: 86400
